# Generated by Django 5.0.4 on 2024-05-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/products'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='product1',
        ),
    ]
